site_name: "ICN Documentation"
site_url: "http://localhost:8000"
theme:
  name: material

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Workflows: workflows.md
  - Testing Overview: testing_overview.md
  - Blockchain:
      - Overview: blockchain/README.md
      - Blockchain: blockchain/blockchain.md
      - Utils:
          - Overview: blockchain/utils/README.md
          - Metrics: blockchain/utils/metrics.md
          - Validation: blockchain/utils/validation.md
          - Crypto: blockchain/utils/crypto.md
      - Core:
          - Overview: blockchain/core/README.md
          - Node: blockchain/core/node.md
          - Block: blockchain/core/block.md
          - Transaction: blockchain/core/transaction.md
          - Shard:
              - Overview: blockchain/core/shard/README.md
              - Validation Manager: blockchain/core/shard/validation_manager.md
              - Transaction Manager: blockchain/core/shard/transaction_manager.md
              - State Manager: blockchain/core/shard/state_manager.md
  - DID:
      - Overview: did/README.md
      - DID: did/did.md
      - Registry: did/registry.md
  - API:
      - Overview: api/README.md
      - Server: api/server.md
  - Tests:
      - Overview: tests/README.md
      - Unit Tests:
          - Test Blockchain: tests/unit/test_blockchain.md
          - Test Node: tests/unit/test_node.md
      - Integration Tests:
          - Test Consensus Mechanism: tests/integration/test_consensus_mechanism.md
          - Test Shard Management: tests/integration/test_shard_management.md
      - Performance Tests:
          - Test Stress Resilience: tests/performance/test_stress_resilience.md
